set(MAX_COMPONENT_TYPES 64 CACHE STRING "")
add_definitions(-DMAX_COMPONENT_TYPES=${MAX_COMPONENT_TYPES})

set(MAX_SYSTEM_TYPES 64 CACHE STRING "")
add_definitions(-DMAX_SYSTEM_TYPES=${MAX_SYSTEM_TYPES})

set(DEFAULT_COMPONENTSTORAGE_MEMORY 65536 CACHE STRING "")
add_definitions(-DDEFAULT_COMPONENTSTORAGE_MEMORY=${DEFAULT_COMPONENTSTORAGE_MEMORY})

set(DEFAULT_INITIAL_ENTITIES_CAPACITY 16 CACHE STRING "")
add_definitions(-DDEFAULT_INITIAL_ENTITIES_CAPACITY=${DEFAULT_INITIAL_ENTITIES_CAPACITY})
