set(CFL_MAX_COMPONENT_TYPES 64 CACHE STRING "")
add_definitions(-DCFL_MAX_COMPONENT_TYPES=${CFL_MAX_COMPONENT_TYPES})

set(CFL_MAX_SYSTEM_TYPES 64 CACHE STRING "")
add_definitions(-DCFL_MAX_SYSTEM_TYPES=${CFL_MAX_SYSTEM_TYPES})

set(CFL_DEFAULT_COMPONENTSTORAGE_MEMORY 65536 CACHE STRING "")
add_definitions(-DCFL_DEFAULT_COMPONENTSTORAGE_MEMORY=${CFL_DEFAULT_COMPONENTSTORAGE_MEMORY})

set(CFL_DEFAULT_INITIAL_ENTITIES_CAPACITY 16 CACHE STRING "")
add_definitions(-DCFL_DEFAULT_INITIAL_ENTITIES_CAPACITY=${CFL_DEFAULT_INITIAL_ENTITIES_CAPACITY})

set(CFL_CORE_ASSETS_DIR ${CMAKE_CURRENT_SOURCE_DIR}/assets CACHE STRING "Path to the core assets directory. Should be assets/")
add_definitions(-DCFL_CORE_ASSETS_DIR="${CFL_CORE_ASSETS_DIR}")
